[strings]
SETTINGS_TITLE = "Settings"
LANGUAGE = "Language:"
AUTO_UPDATE = "Auto update:"
CLOSE_ON_LAUNCH = "Close launcher after launch:"
RESET = "Reset settings"
IMPORT = "Import"
EXPORT = "Export"
SUCCESS_SAVE = "Settings saved"
ERROR = "Error saving settings"
CLOSE_ON_LAUNCH_HINT = "If enabled, launcher will close after game start."
DASHBOARD_TITLE = "Welcome to SectLauncher"
DASHBOARD_SUBTITLE = "Your Minecraft launcher"
ABOUT_TITLE = "About"
ABOUT_VERSION = "SectLauncher v1.0.0"
PACKS_TITLE = "My packs"
BUTTON_CREATE_PACK = "Create pack"
CREATE_PACK_TITLE = "Create pack"
FIELD_NAME = "Name"
FIELD_DESCRIPTION = "Description"
STATUS_READY = "Ready"
STATUS_VERSION = "v0.0.1 alpha"
ERROR_LOADING = "Loading error"
RETRY = "Retry"
EMPTY_PACKS = "You have no packs yet"
MINECRAFT_TITLE = "Minecraft Versions"
GENERAL_CATEGORY = "General"
UPDATE_CATEGORY = "Updates"
BEHAVIOR_CATEGORY = "Behavior"
ADVANCED_CATEGORY = "Advanced"
LANGUAGE_LABEL = "Interface language"
AUTO_UPDATE_LABEL = "Auto update"
CLOSE_ON_LAUNCH_LABEL = "Close launcher after launch"
ADVANCED_PLACEHOLDER = "Advanced/experimental settings will appear here"
CREATE_FIRST_PACK = "Create first pack"
SEARCH_VERSION_LABEL = "Search by version"
DOWNLOAD_LABEL = "Download"
LOGO_TEXT = "SECT" # Mis
sing localization strings
DELETE_PACK_CONFIRM = "Delete pack?"
DELETE = "Delete"
CANCEL = "Cancel"
PACK_CREATED_SUCCESS = "Pack created successfully!"
PACK_DELETED_SUCCESS = "Pack deleted"
INSTANCE_CREATED_SUCCESS = "Instance created"
INSTANCE_DELETED_SUCCESS = "Instance deleted"
DOWNLOAD_STARTING = "Starting download..."
DOWNLOAD_CLIENT = "Downloading Minecraft client..."
DOWNLOAD_LIBRARIES = "Downloading libraries..."
DOWNLOAD_ASSETS = "Downloading assets..."
DOWNLOAD_COMPLETE = "Download complete!"
LAUNCH_SUCCESS = "Game launched"
LAUNCH_ERROR = "Launch error"
PLAY = "Play"
STOP = "Stop"
INSTALL = "Install"
CREATE_INSTANCE = "Create instance"
INSTANCES_COUNT = "Instances"
VERSION_LABEL = "Version"
NO_INSTANCES = "No instances"
READY_TO_PLAY = "Ready to play"
RUNNING = "Running"
DOWNLOADING = "Downloading..."
INSTALLING = "Installing..."
ERROR_STATUS = "Error"
NOT_INSTALLED = "Not installed"