[strings]
SETTINGS_TITLE = "Настройки"
LANGUAGE = "Язык:"
AUTO_UPDATE = "Автообновления:"
CLOSE_ON_LAUNCH = "Закрывать лаунчер после запуска:"
RESET = "Сбросить настройки"
IMPORT = "Импортировать"
EXPORT = "Экспортировать"
SUCCESS_SAVE = "Настройки сохранены"
ERROR = "Ошибка при сохранении настроек"
CLOSE_ON_LAUNCH_HINT = "Если включено, лаунчер закроется после запуска игры."
DASHBOARD_TITLE = "Добро пожаловать в SectLauncher"
DASHBOARD_SUBTITLE = "Ваш Minecraft лаунчер"
ABOUT_TITLE = "О программе"
ABOUT_VERSION = "SectLauncher v1.0.0"
PACKS_TITLE = "Мои паки"
BUTTON_CREATE_PACK = "Создать пак"
CREATE_PACK_TITLE = "Создание пака"
FIELD_NAME = "Наименование"
FIELD_DESCRIPTION = "Описание"
STATUS_READY = "Готов к работе"
STATUS_VERSION = "v0.0.1 alpha"
ERROR_LOADING = "Ошибка загрузки"
RETRY = "Повторить"
EMPTY_PACKS = "У вас пока нет паков"
MINECRAFT_TITLE = "Версии Minecraft"
GENERAL_CATEGORY = "Общие"
UPDATE_CATEGORY = "Обновления"
BEHAVIOR_CATEGORY = "Поведение"
ADVANCED_CATEGORY = "Расширенные"
LANGUAGE_LABEL = "Язык интерфейса"
AUTO_UPDATE_LABEL = "Автообновления"
CLOSE_ON_LAUNCH_LABEL = "Закрывать лаунчер после запуска"
ADVANCED_PLACEHOLDER = "Расширенные/экспериментальные настройки появятся здесь" 
CREATE_FIRST_PACK = "Создать первый пак"
SEARCH_VERSION_LABEL = "Поиск по версии"
DOWNLOAD_LABEL = "Скачать"
LOGO_TEXT = "SECT"
# Дополнительные строки для улучшенного функционала
PACK_CREATED_SUCCESS = "Пак успешно создан!"
PACK_DELETED_SUCCESS = "Пак удален"
INSTANCE_CREATED_SUCCESS = "Инстанс создан"
INSTANCE_DELETED_SUCCESS = "Инстанс удален"
DOWNLOAD_STARTING = "Начинаем скачивание..."
DOWNLOAD_CLIENT = "Скачиваем клиент Minecraft..."
DOWNLOAD_LIBRARIES = "Скачиваем библиотеки..."
DOWNLOAD_ASSETS = "Скачиваем ресурсы..."
DOWNLOAD_COMPLETE = "Скачивание завершено!"
LAUNCH_SUCCESS = "Игра запущена"
LAUNCH_ERROR = "Ошибка запуска игры"
DELETE_PACK_CONFIRM = "Вы уверены, что хотите удалить этот пак?"
DELETE_INSTANCE_CONFIRM = "Вы уверены, что хотите удалить этот инстанс?"
PLAY = "Играть"
STOP = "Остановить"
INSTALL = "Установить"
CREATE_INSTANCE = "Создать инстанс"
INSTANCES_COUNT = "Инстансов"
VERSION_LABEL = "Версия"
NO_INSTANCES = "Нет инстансов"
READY_TO_PLAY = "Готов к игре"
RUNNING = "Запущен"
DOWNLOADING = "Скачивание..."
INSTALLING = "Установка..."
ERROR_STATUS = "Ошибка"
NOT_INSTALLED = "Не установлен"